services:
  - type: web
    name: inform-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    branch: main
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
