from inform.exercise import Exercise

# Stopgap pool: the paper (§3.2.2) specifies Module 3 should query the
# hasaneyldrm/exercises-dataset, which isn't vendored in this repo yet
# (tracked separately). This hand-picked set exists only to unblock
# demos/manual testing of run_pipeline end-to-end — swap for the real
# dataset loader once it lands; recommend_exercises itself doesn't change.
DEFAULT_EXERCISE_POOL: list[Exercise] = [
    Exercise(
        name="Single-arm dumbbell row",
        target="lats",
        body_part="upper arms",
        equipment="dumbbell",
        secondary_muscles=["biceps"],
        movement_type="corrective_unilateral",
    ),
    Exercise(
        name="Single-arm overhead press",
        target="deltoids",
        body_part="upper arms",
        equipment="dumbbell",
        secondary_muscles=["triceps"],
        movement_type="corrective_unilateral",
    ),
    Exercise(
        name="Single-arm wrist curl",
        target="forearms",
        body_part="lower arms",
        equipment="dumbbell",
        secondary_muscles=[],
        movement_type="corrective_unilateral",
    ),
    Exercise(
        name="Bulgarian split squat",
        target="quadriceps",
        body_part="upper legs",
        equipment="body weight",
        secondary_muscles=["glutes"],
        movement_type="corrective_unilateral",
    ),
    Exercise(
        name="Single-leg press",
        target="quadriceps",
        body_part="upper legs",
        equipment="leverage machine",
        secondary_muscles=["glutes", "hamstrings"],
        movement_type="corrective_unilateral",
    ),
    Exercise(
        name="Single-leg calf raise",
        target="calves",
        body_part="lower legs",
        equipment="body weight",
        secondary_muscles=[],
        movement_type="corrective_unilateral",
    ),
    Exercise(
        name="Barbell back squat",
        target="quadriceps",
        body_part="upper legs",
        equipment="barbell",
        secondary_muscles=["glutes", "hamstrings"],
        movement_type="bilateral_compound",
    ),
    Exercise(
        name="Bench press",
        target="pectorals",
        body_part="chest",
        equipment="barbell",
        secondary_muscles=["triceps"],
        movement_type="bilateral_compound",
    ),
    Exercise(
        name="Deadlift",
        target="glutes",
        body_part="upper legs",
        equipment="barbell",
        secondary_muscles=["hamstrings", "lower back"],
        movement_type="bilateral_compound",
    ),
    Exercise(
        name="Overhead press",
        target="deltoids",
        body_part="shoulders",
        equipment="barbell",
        secondary_muscles=["triceps"],
        movement_type="bilateral_compound",
    ),
    Exercise(
        name="Pull-up",
        target="lats",
        body_part="back",
        equipment="body weight",
        secondary_muscles=["biceps"],
        movement_type="bilateral_compound",
    ),
    Exercise(
        name="Barbell row",
        target="lats",
        body_part="back",
        equipment="barbell",
        secondary_muscles=["biceps"],
        movement_type="bilateral_compound",
    ),
    Exercise(
        name="Rowing sprint intervals",
        target="cardiovascular system",
        body_part="cardio",
        equipment="rowing machine",
        secondary_muscles=[],
        movement_type="cardio_hiit",
    ),
    Exercise(
        name="Burpees",
        target="cardiovascular system",
        body_part="cardio",
        equipment="body weight",
        secondary_muscles=[],
        movement_type="cardio_hiit",
    ),
    Exercise(
        name="Battle ropes",
        target="cardiovascular system",
        body_part="cardio",
        equipment="rope",
        secondary_muscles=[],
        movement_type="cardio_hiit",
    ),
    Exercise(
        name="Jump rope intervals",
        target="cardiovascular system",
        body_part="cardio",
        equipment="jump rope",
        secondary_muscles=[],
        movement_type="cardio_hiit",
    ),
]
