"""create accounts and scans

Revision ID: e627578b4362
Revises: 
Create Date: 2026-09-19 00:04:11.587859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e627578b4362'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_device', sa.String(), nullable=True),
    sa.Column('sample_id', sa.String(), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('measured', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_inbody', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('corrected_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nutrition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative_text', sa.Text(), nullable=False),
    sa.Column('narrative_source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_account_id'), 'scans', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_account_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
