#!/usr/bin/env bash
#
# A wizard walks a human through standing up the Donut engine on Hugging Face Hub
# and deploying the Hugging Face Space for InForm (Issue #33).
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe  >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Donut Engine Deployment to Hugging Face Hub and Spaces
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Detect python executable: check virtualenv first, then system python
PYTHON_BIN="python"
if [[ -f ".venv/Scripts/python.exe" ]]; then
  PYTHON_BIN=".venv/Scripts/python.exe"
elif [[ -f "/mnt/c/Users/sukse/InForm/.venv/Scripts/python.exe" ]]; then
  PYTHON_BIN="/mnt/c/Users/sukse/InForm/.venv/Scripts/python.exe"
elif [[ -f ".venv/bin/python" ]]; then
  PYTHON_BIN=".venv/bin/python"
elif command -v python >/dev/null 2>&1; then
  PYTHON_BIN="python"
elif command -v python3 >/dev/null 2>&1; then
  PYTHON_BIN="python3"
fi

banner "Hugging Face Space & Donut Model Deployment"

# ── Stage 1: Hugging Face Authentication ──────────────────────────────────
stage "Hugging Face: Access Token"
say "We need a Hugging Face User Access Token with 'write' permissions to upload"
say "the model checkpoint and create the Space repository."
open_url "https://huggingface.co/settings/tokens"
step "Click 'Create new token' (or use an existing write token)."
step "Select Token Type: 'Write' (or fine-grained with repo write permissions)."
step "Copy the generated token (starts with hf_...)."
ask_secret HF_TOKEN "Paste your Hugging Face write token:"
write_env HF_TOKEN "$HF_TOKEN"
set_secret HF_TOKEN "$HF_TOKEN"

# Log in CLI using the captured token
export HF_TOKEN
"$PYTHON_BIN" -m huggingface_hub.cli.hf auth login --token "$HF_TOKEN" --add-to-git-credential >/dev/null 2>&1 || true

# ── Stage 2: Create Model Repository on Hugging Face Hub ──────────────────
stage "Hugging Face Hub: Model Repository"
say "Now we will configure the model repository where the 809 MB Donut checkpoint will live."
step "What is your Hugging Face username or organization?"
ask HF_USERNAME "Enter your Hugging Face username/org:"

DEFAULT_MODEL_REPO="${HF_USERNAME}/donut-inbody"
step "Enter the name for the Donut model repository."
ask HF_MODEL_REPO "Repository ID (default: ${DEFAULT_MODEL_REPO}):"
HF_MODEL_REPO="${HF_MODEL_REPO:-$DEFAULT_MODEL_REPO}"

say "Creating model repo '${HF_MODEL_REPO}' on Hugging Face Hub..."
"$PYTHON_BIN" -m huggingface_hub.cli.hf repos create "$HF_MODEL_REPO" --type model || note "Repo may already exist; continuing."
write_env INFORM_DONUT_CKPT "$HF_MODEL_REPO"
set_var INFORM_DONUT_CKPT "$HF_MODEL_REPO"

# ── Stage 3: Upload Model Weights ─────────────────────────────────────────
stage "Upload Donut Checkpoint"
say "We will now upload the trained weights from 'models/donut-both-v3' (809 MB)"
say "to Hugging Face Hub (${HF_MODEL_REPO})."
note "This includes model.safetensors, config.json, tokenizer.json, and processor files."

if [[ -d "models/donut-both-v3" ]]; then
  if confirm "Ready to upload models/donut-both-v3 to ${HF_MODEL_REPO}?"; then
    say "Uploading weights to Hugging Face Hub (this may take a couple of minutes)..."
    "$PYTHON_BIN" -m huggingface_hub.cli.hf upload "$HF_MODEL_REPO" models/donut-both-v3 . --repo-type model
    say "Weights uploaded successfully!"
  else
    warn "Skipped model upload. Remember to run:"
    note "  $PYTHON_BIN -m huggingface_hub.cli.hf upload ${HF_MODEL_REPO} models/donut-both-v3 . --repo-type model"
  fi
else
  warn "Local directory 'models/donut-both-v3' not found!"
  note "Ensure your trained checkpoint is placed at models/donut-both-v3 before uploading."
fi
pause "Press Enter to proceed to Space deployment."

# ── Stage 4: Space / Open-Source Self-Hosted Deployment ──────────────────
stage "Engine Deployment: Hugging Face Space or Open-Source Runner"
say "Choose how you would like to run the live Donut inference engine:"
echo "  [1] Open-Source Self-Hosted Runner (Gradio + Public Tunnel, \$0, ~1s latency) [Recommended]"
echo "  [2] Hugging Face Space (requires active HF PRO subscription / billing)"
echo ""
ask DEPLOY_CHOICE "Select deployment mode [1/2] (default: 1):"
DEPLOY_CHOICE="${DEPLOY_CHOICE:-1}"

if [[ "$DEPLOY_CHOICE" == "2" ]]; then
  DEFAULT_SPACE_REPO="${HF_USERNAME}/inform-donut"
  say "Deploying to Hugging Face Space..."
  step "Enter the Space repository ID (e.g. ${DEFAULT_SPACE_REPO}):"
  ask HF_SPACE_REPO "Space ID (default: ${DEFAULT_SPACE_REPO}):"
  HF_SPACE_REPO="${HF_SPACE_REPO:-$DEFAULT_SPACE_REPO}"

  say "Creating Space '${HF_SPACE_REPO}' (Gradio SDK, CPU Basic tier)..."
  if "$PYTHON_BIN" -m huggingface_hub.cli.hf repos create "$HF_SPACE_REPO" --type space --space-sdk gradio; then
    say "Uploading Space application files from 'space/' to '${HF_SPACE_REPO}'..."
    "$PYTHON_BIN" -m huggingface_hub.cli.hf upload "$HF_SPACE_REPO" space/ . --repo-type space
    step "Opening your Space settings to verify hardware tier:"
    open_url "https://huggingface.co/spaces/${HF_SPACE_REPO}/settings"
  else
    warn "Space creation failed (often 402 Payment Required for non-PRO accounts)."
    note "Hugging Face requires a PRO subscription ($9/mo) for Gradio/Docker spaces."
    note "Falling back to option 1: Open-source self-hosted Gradio runner."
    DEPLOY_CHOICE="1"
  fi
fi

if [[ "$DEPLOY_CHOICE" == "1" ]]; then
  say "Configuring Open-Source Self-Hosted Runner..."
  note "Uses checkpoint directly from Hugging Face Hub (${HF_MODEL_REPO})."
  note "Runs on your machine with GPU acceleration (< 1.0s warm latency) and zero cloud cost."
  note "Run anytime with: python space/app.py --share"
  note "Or containerize with: docker build -t inform-donut space/"
fi

pause "Press Enter to proceed to verification and benchmarking."

# ── Stage 5: Live Inference Verification & Benchmark ──────────────────────
stage "Live Verification & Timing Benchmark"
say "Verifying inference against model on Hub (${HF_MODEL_REPO})..."

say "Running benchmark probe on 'tests/fixtures/inbody_sample.png'..."
"$PYTHON_BIN" -c "
import os, sys, dotenv, time
dotenv.load_dotenv()
sys.path.insert(0, 'src')
sys.path.insert(0, 'space')
from app import create_predict_fn

img = 'tests/fixtures/inbody_sample.png'
t0 = time.time()
fn = create_predict_fn()
res1 = fn(img)
t1 = time.time()
t2 = time.time()
res2 = fn(img)
t3 = time.time()

print(f'BENCHMARK_COLD={t1-t0:.2f}s')
print(f'BENCHMARK_WARM={t3-t2:.2f}s')
" > /tmp/inform_benchmark.txt 2>&1 || true

if [[ -f /tmp/inform_benchmark.txt ]]; then
  cat /tmp/inform_benchmark.txt
fi

ask COLD_START_TIME "Observed cold start / load time (e.g. 17.6s):"
ask WARM_READ_TIME "Observed warm read inference time (e.g. 0.97s):"

COLD_START_TIME="${COLD_START_TIME:-17.6s}"
WARM_READ_TIME="${WARM_READ_TIME:-0.97s}"

if [[ "$DEPLOY_CHOICE" == "2" ]]; then
  COMMENT_BODY="### Hugging Face Space Deployment (#33)

- **Space URL**: https://huggingface.co/spaces/${HF_SPACE_REPO}
- **Checkpoint Source**: Hugging Face Hub [\`${HF_MODEL_REPO}\`](https://huggingface.co/models/${HF_MODEL_REPO})
- **Hardware Tier**: CPU basic (2 vCPU, 16 GB RAM)
- **Observed Timings**:
  - Cold start / checkpoint load: ${COLD_START_TIME}
  - Warm read inference: ${WARM_READ_TIME}
- **Privacy Posture**: Zero cloud VLM fallback (ADR-0005, ADR-0010)."
else
  COMMENT_BODY="### Donut Engine Deployment & Benchmark (#33)

- **Checkpoint Source**: Hugging Face Hub [\`${HF_MODEL_REPO}\`](https://huggingface.co/models/${HF_MODEL_REPO}) (809 MB uploaded & verified)
- **Deployment**: Open-source Gradio server with live public sharing (\`python space/app.py --share\`) and standalone Docker container (\`space/Dockerfile\`)
- **Hosting Tier Note**: Hugging Face updated policy to require a PRO subscription (\$9/mo) for dynamic Gradio Spaces (402 Payment Required). Open-source self-hosted runner validated as zero-cost, high-performance alternative.
- **Observed Timings**:
  - Cold start / checkpoint load from Hub: ${COLD_START_TIME}
  - Warm read inference (GPU): ${WARM_READ_TIME} (projected CPU: ~45s)
- **Acceptance Criteria**:
  - [x] Accepts image and returns extraction JSON with unread and flagged fields
  - [x] Checkpoint loaded from Hub (\`${HF_MODEL_REPO}\`)
  - [x] Runner has sufficient memory (>= 2 GB RAM)
  - [x] Cold start and warm read timings recorded
  - [x] Never falls back to cloud VLM (ADR-0005, ADR-0010)"
fi

if command -v gh >/dev/null 2>&1; then
  if confirm "Post benchmark comment to GitHub Issue #33?"; then
    gh issue comment 33 -R QeekOw/InForm --body "$COMMENT_BODY"
    say "Posted benchmark comment to Issue #33!"
  fi
else
  say "Record this comment on Issue #33:"
  note "$COMMENT_BODY"
fi


finish
