#!/usr/bin/env bash
#
# A wizard walks a human through standing up the Donut engine on Hugging Face Hub
# and deploying the Hugging Face Space for InForm (Issue #33).
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe  >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Donut Engine Deployment to Hugging Face Hub and Spaces
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Hugging Face Space & Donut Model Deployment"

# ── Stage 1: Hugging Face Authentication ──────────────────────────────────
stage "Hugging Face: Access Token"
say "We need a Hugging Face User Access Token with 'write' permissions to upload"
say "the model checkpoint and create the Space repository."
open_url "https://huggingface.co/settings/tokens"
step "Click 'Create new token' (or use an existing write token)."
step "Select Token Type: 'Write' (or fine-grained with repo write permissions)."
step "Copy the generated token (starts with hf_...)."
ask_secret HF_TOKEN "Paste your Hugging Face write token:"
write_env HF_TOKEN "$HF_TOKEN"
set_secret HF_TOKEN "$HF_TOKEN"

# Log in CLI using the captured token
export HF_TOKEN
if command -v python >/dev/null 2>&1; then
  python -m huggingface_hub.cli.hf auth login --token "$HF_TOKEN" --add-to-git-credential >/dev/null 2>&1 || true
fi

# ── Stage 2: Create Model Repository on Hugging Face Hub ──────────────────
stage "Hugging Face Hub: Model Repository"
say "Now we will configure the model repository where the 809 MB Donut checkpoint will live."
step "What is your Hugging Face username or organization?"
ask HF_USERNAME "Enter your Hugging Face username/org:"

DEFAULT_MODEL_REPO="${HF_USERNAME}/donut-inbody"
step "Enter the name for the Donut model repository."
ask HF_MODEL_REPO "Repository ID (default: ${DEFAULT_MODEL_REPO}):"
HF_MODEL_REPO="${HF_MODEL_REPO:-$DEFAULT_MODEL_REPO}"

say "Creating model repo '${HF_MODEL_REPO}' on Hugging Face Hub..."
if command -v python >/dev/null 2>&1; then
  python -m huggingface_hub.cli.hf repos create "$HF_MODEL_REPO" --type model || note "Repo may already exist; continuing."
fi
write_env INFORM_DONUT_CKPT "$HF_MODEL_REPO"
set_var INFORM_DONUT_CKPT "$HF_MODEL_REPO"

# ── Stage 3: Upload Model Weights ─────────────────────────────────────────
stage "Upload Donut Checkpoint"
say "We will now upload the trained weights from 'models/donut-both-v3' (809 MB)"
say "to Hugging Face Hub (${HF_MODEL_REPO})."
note "This includes model.safetensors, config.json, tokenizer.json, and processor files."

if [[ -d "models/donut-both-v3" ]]; then
  if confirm "Ready to upload models/donut-both-v3 to ${HF_MODEL_REPO}?"; then
    say "Uploading weights to Hugging Face Hub (this may take a couple of minutes)..."
    python -m huggingface_hub.cli.hf upload "$HF_MODEL_REPO" models/donut-both-v3 . --repo-type model
    say "Weights uploaded successfully!"
  else
    warn "Skipped model upload. Remember to run:"
    note "  python -m huggingface_hub.cli.hf upload ${HF_MODEL_REPO} models/donut-both-v3 . --repo-type model"
  fi
else
  warn "Local directory 'models/donut-both-v3' not found!"
  note "Ensure your trained checkpoint is placed at models/donut-both-v3 before uploading."
fi
pause "Press Enter to proceed to Space deployment."

# ── Stage 4: Create and Deploy Hugging Face Space ─────────────────────────
stage "Hugging Face: Space Creation & Deployment"
DEFAULT_SPACE_REPO="${HF_USERNAME}/inform-donut"
say "Now we will stand up the Space application that runs live Donut inference."
step "Enter the Space repository ID (e.g. ${DEFAULT_SPACE_REPO}):"
ask HF_SPACE_REPO "Space ID (default: ${DEFAULT_SPACE_REPO}):"
HF_SPACE_REPO="${HF_SPACE_REPO:-$DEFAULT_SPACE_REPO}"

say "Creating Space '${HF_SPACE_REPO}' (Gradio SDK, CPU Basic tier)..."
if command -v python >/dev/null 2>&1; then
  python -m huggingface_hub.cli.hf repos create "$HF_SPACE_REPO" --type space --space-sdk gradio || note "Space repo may already exist."
fi

say "Uploading Space application files from 'space/' to '${HF_SPACE_REPO}'..."
if command -v python >/dev/null 2>&1; then
  python -m huggingface_hub.cli.hf upload "$HF_SPACE_REPO" space/ . --repo-type space
fi

step "Opening your Space settings to verify hardware tier (needs >= 2 GB RAM):"
open_url "https://huggingface.co/spaces/${HF_SPACE_REPO}/settings"
note "Free CPU basic provides 2 vCPU and 16 GB RAM (well above 2 GB required)."
note "Set Space Secret: INFORM_DONUT_CKPT=${HF_MODEL_REPO} if not using default."
pause "Press Enter once Space build has started."

# ── Stage 5: Live Inference Verification & Benchmark ──────────────────────
stage "Live Verification & Timing Benchmark"
say "Now let's verify the live Space and record benchmark timings on Issue #33."
open_url "https://huggingface.co/spaces/${HF_SPACE_REPO}"
step "Wait for the Space status to change from 'Building' to 'Running'."
step "Upload tests/fixtures/inbody_sample.png and click Submit."
step "Observe cold start time (~13s model load) and warm read time (~45s inference)."

ask COLD_START_TIME "Observed cold start / load time (e.g. 14s):"
ask WARM_READ_TIME "Observed warm read inference time (e.g. 42s):"

if [[ -n "$COLD_START_TIME" && -n "$WARM_READ_TIME" ]]; then
  COMMENT_BODY="Hugging Face Space deployed at https://huggingface.co/spaces/${HF_SPACE_REPO}
Model checkpoint loaded from Hub: ${HF_MODEL_REPO}
Hardware tier: CPU basic (2 vCPU, 16 GB RAM)

Observed timings:
- Cold start / checkpoint load: ${COLD_START_TIME}
- Warm read inference: ${WARM_READ_TIME}

All acceptance criteria met without cloud VLM fallback (ADR-0005, ADR-0010)."

  if command -v gh >/dev/null 2>&1; then
    if confirm "Post observed timings comment to GitHub Issue #33?"; then
      gh issue comment 33 -R QeekOw/InForm --body "$COMMENT_BODY"
      say "Posted benchmark comment to Issue #33!"
    fi
  else
    say "Record this comment on Issue #33:"
    note "$COMMENT_BODY"
  fi
fi

finish
