#!/usr/bin/env python
"""Generate pre-computed Sample sheet extractions using the active checkpoint (Issue #32).

Sample sheets in the gallery are answered from a stored reading rather than by running
the model on every visit. The stored readings are provably generated by this committed
script, recording which checkpoint produced them, and recording clean reads, unread fields,
suspect flagged fields, and model refusals exactly as produced.

Usage:
    # Regenerate committed artifact:
    python scripts/generate_sample_extractions.py

    # Verify committed artifact matches what the script currently produces (CI check):
    python scripts/generate_sample_extractions.py --check
"""

import argparse
import json
import sys
from pathlib import Path

# Add src to sys.path so inform can be imported when run directly
_repo_src = Path(__file__).resolve().parent.parent / "src"
if _repo_src.exists() and str(_repo_src) not in sys.path:
    sys.path.insert(0, str(_repo_src))

from inform.samples import (
    default_extractions_path,
    default_manifest_path,
    diff_extractions,
    generate_extractions,
    load_extractions,
    load_manifest,
)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate or verify pre-computed Sample sheet extractions."
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=default_manifest_path(),
        help="Path to sample manifest.json (default: data/samples/manifest.json)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=default_extractions_path(),
        help="Path to output extractions.json (default: data/samples/extractions.json)",
    )
    parser.add_argument(
        "--checkpoint",
        type=str,
        default=None,
        help="Checkpoint identifier or local directory path",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check that the committed artifact matches what the script produces without overwriting",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated JSON to stdout instead of writing to file",
    )
    args = parser.parse_args()

    manifest = load_manifest(args.manifest)
    print(f"Loaded manifest with {len(manifest.samples)} samples from {args.manifest}")

    print("Running checkpoint extraction across all manifest sheets...")
    candidate_artifact = generate_extractions(
        manifest,
        checkpoint_id=args.checkpoint,
        base_dir=args.manifest.parent.parent.parent,
    )

    if args.check:
        if not args.output.exists():
            print(f"ERROR: Committed extractions artifact not found at {args.output}")
            return 1

        committed_artifact = load_extractions(args.output)
        diffs = diff_extractions(committed_artifact, candidate_artifact)
        if diffs:
            print(
                f"FAIL: Committed extractions in {args.output} differ from script output ({len(diffs)} diffs):"
            )
            for d in diffs:
                print(f"  - {d}")
            return 1

        print(
            f"OK: Committed extractions in {args.output} match script output exactly for checkpoint '{committed_artifact.checkpoint}'."
        )
        return 0

    if args.dry_run:
        print(candidate_artifact.model_dump_json(indent=2))
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(candidate_artifact.model_dump_json(indent=2), encoding="utf-8")
    print(
        f"Wrote pre-computed extractions ({len(candidate_artifact.extractions)} entries) to {args.output}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
